### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by perrygeo** [perrygeo/simanneal#30]
See https://travis-ci.org/perrygeo/simanneal/jobs/566946682 and #28

**Comment by deckar01** [comment]
I turned on Travis for my fork and the tests passed. There were a few differences in the environments. Mine defaulted to `xenial` and the failed build defaulted to `trusty`. I was able to reproduce a build error by setting the `dist` to `trusty` in the config.

The underlying issue seems to be `pytest-cov`'s required version range for `pytest` being updated to `>=3.6.0`. The `trusty` image comes with `pytest` `3.3.0` preinstalled and `pip` errors instead of updating the existing install.

Hard coding the `dist` would temporarily fix the issue, but dependencies could get out of sync again as preinstalled packages and dependencies change. To avoid this occurring again, the best fix is probably to force pip to upgrade existing dependencies.
